package com.devix.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CatalogoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCatalogoAllPropertiesEquals(Catalogo expected, Catalogo actual) {
        assertCatalogoAutoGeneratedPropertiesEquals(expected, actual);
        assertCatalogoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCatalogoAllUpdatablePropertiesEquals(Catalogo expected, Catalogo actual) {
        assertCatalogoUpdatableFieldsEquals(expected, actual);
        assertCatalogoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCatalogoAutoGeneratedPropertiesEquals(Catalogo expected, Catalogo actual) {
        assertThat(actual)
            .as("Verify Catalogo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCatalogoUpdatableFieldsEquals(Catalogo expected, Catalogo actual) {
        assertThat(actual)
            .as("Verify Catalogo relevant properties")
            .satisfies(a -> assertThat(a.getNoCia()).as("check noCia").isEqualTo(expected.getNoCia()))
            .satisfies(a -> assertThat(a.getDescripcion1()).as("check descripcion1").isEqualTo(expected.getDescripcion1()))
            .satisfies(a -> assertThat(a.getDescripcion2()).as("check descripcion2").isEqualTo(expected.getDescripcion2()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getOrden()).as("check orden").isEqualTo(expected.getOrden()))
            .satisfies(a -> assertThat(a.getTexto1()).as("check texto1").isEqualTo(expected.getTexto1()))
            .satisfies(a -> assertThat(a.getTexto2()).as("check texto2").isEqualTo(expected.getTexto2()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCatalogoUpdatableRelationshipsEquals(Catalogo expected, Catalogo actual) {
        assertThat(actual)
            .as("Verify Catalogo relationships")
            .satisfies(a -> assertThat(a.getTipoCatalogo()).as("check tipoCatalogo").isEqualTo(expected.getTipoCatalogo()));
    }
}
