package com.devix.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CentroAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCentroAllPropertiesEquals(Centro expected, Centro actual) {
        assertCentroAutoGeneratedPropertiesEquals(expected, actual);
        assertCentroAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCentroAllUpdatablePropertiesEquals(Centro expected, Centro actual) {
        assertCentroUpdatableFieldsEquals(expected, actual);
        assertCentroUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCentroAutoGeneratedPropertiesEquals(Centro expected, Centro actual) {
        assertThat(actual)
            .as("Verify Centro auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCentroUpdatableFieldsEquals(Centro expected, Centro actual) {
        assertThat(actual)
            .as("Verify Centro relevant properties")
            .satisfies(a -> assertThat(a.getNoCia()).as("check noCia").isEqualTo(expected.getNoCia()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCentroUpdatableRelationshipsEquals(Centro expected, Centro actual) {
        assertThat(actual)
            .as("Verify Centro relationships")
            .satisfies(a -> assertThat(a.getCompania()).as("check compania").isEqualTo(expected.getCompania()));
    }
}
