package com.devix.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CompaniaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompaniaAllPropertiesEquals(Compania expected, Compania actual) {
        assertCompaniaAutoGeneratedPropertiesEquals(expected, actual);
        assertCompaniaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompaniaAllUpdatablePropertiesEquals(Compania expected, Compania actual) {
        assertCompaniaUpdatableFieldsEquals(expected, actual);
        assertCompaniaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompaniaAutoGeneratedPropertiesEquals(Compania expected, Compania actual) {
        assertThat(actual)
            .as("Verify Compania auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompaniaUpdatableFieldsEquals(Compania expected, Compania actual) {
        assertThat(actual)
            .as("Verify Compania relevant properties")
            .satisfies(a -> assertThat(a.getNoCia()).as("check noCia").isEqualTo(expected.getNoCia()))
            .satisfies(a -> assertThat(a.getDni()).as("check dni").isEqualTo(expected.getDni()))
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDireccion()).as("check direccion").isEqualTo(expected.getDireccion()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getTelefono()).as("check telefono").isEqualTo(expected.getTelefono()))
            .satisfies(a -> assertThat(a.getPathImage()).as("check pathImage").isEqualTo(expected.getPathImage()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCompaniaUpdatableRelationshipsEquals(Compania expected, Compania actual) {
        // empty method
    }
}
