package com.devix.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DetalleFacturaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetalleFacturaAllPropertiesEquals(DetalleFactura expected, DetalleFactura actual) {
        assertDetalleFacturaAutoGeneratedPropertiesEquals(expected, actual);
        assertDetalleFacturaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetalleFacturaAllUpdatablePropertiesEquals(DetalleFactura expected, DetalleFactura actual) {
        assertDetalleFacturaUpdatableFieldsEquals(expected, actual);
        assertDetalleFacturaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetalleFacturaAutoGeneratedPropertiesEquals(DetalleFactura expected, DetalleFactura actual) {
        assertThat(actual)
            .as("Verify DetalleFactura auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetalleFacturaUpdatableFieldsEquals(DetalleFactura expected, DetalleFactura actual) {
        assertThat(actual)
            .as("Verify DetalleFactura relevant properties")
            .satisfies(a -> assertThat(a.getNoCia()).as("check noCia").isEqualTo(expected.getNoCia()))
            .satisfies(a -> assertThat(a.getCantidad()).as("check cantidad").isEqualTo(expected.getCantidad()))
            .satisfies(a -> assertThat(a.getPrecioUnitario()).as("check precioUnitario").isEqualTo(expected.getPrecioUnitario()))
            .satisfies(a -> assertThat(a.getSubtotal()).as("check subtotal").isEqualTo(expected.getSubtotal()))
            .satisfies(a -> assertThat(a.getDescuento()).as("check descuento").isEqualTo(expected.getDescuento()))
            .satisfies(a -> assertThat(a.getImpuesto()).as("check impuesto").isEqualTo(expected.getImpuesto()))
            .satisfies(a -> assertThat(a.getTotal()).as("check total").isEqualTo(expected.getTotal()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetalleFacturaUpdatableRelationshipsEquals(DetalleFactura expected, DetalleFactura actual) {
        assertThat(actual)
            .as("Verify DetalleFactura relationships")
            .satisfies(a -> assertThat(a.getFactura()).as("check factura").isEqualTo(expected.getFactura()))
            .satisfies(a -> assertThat(a.getProducto()).as("check producto").isEqualTo(expected.getProducto()));
    }
}
