package com.devix.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DocumentoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentoAllPropertiesEquals(Documento expected, Documento actual) {
        assertDocumentoAutoGeneratedPropertiesEquals(expected, actual);
        assertDocumentoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentoAllUpdatablePropertiesEquals(Documento expected, Documento actual) {
        assertDocumentoUpdatableFieldsEquals(expected, actual);
        assertDocumentoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentoAutoGeneratedPropertiesEquals(Documento expected, Documento actual) {
        assertThat(actual)
            .as("Verify Documento auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentoUpdatableFieldsEquals(Documento expected, Documento actual) {
        assertThat(actual)
            .as("Verify Documento relevant properties")
            .satisfies(a -> assertThat(a.getNoCia()).as("check noCia").isEqualTo(expected.getNoCia()))
            .satisfies(a -> assertThat(a.getTipo()).as("check tipo").isEqualTo(expected.getTipo()))
            .satisfies(a -> assertThat(a.getObservacion()).as("check observacion").isEqualTo(expected.getObservacion()))
            .satisfies(a -> assertThat(a.getFechaCreacion()).as("check fechaCreacion").isEqualTo(expected.getFechaCreacion()))
            .satisfies(a -> assertThat(a.getFechaVencimiento()).as("check fechaVencimiento").isEqualTo(expected.getFechaVencimiento()))
            .satisfies(a -> assertThat(a.getPath()).as("check path").isEqualTo(expected.getPath()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDocumentoUpdatableRelationshipsEquals(Documento expected, Documento actual) {
        assertThat(actual)
            .as("Verify Documento relationships")
            .satisfies(a -> assertThat(a.getCliente()).as("check cliente").isEqualTo(expected.getCliente()))
            .satisfies(a -> assertThat(a.getEvento()).as("check evento").isEqualTo(expected.getEvento()));
    }
}
