package com.devix.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EventoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoAllPropertiesEquals(Evento expected, Evento actual) {
        assertEventoAutoGeneratedPropertiesEquals(expected, actual);
        assertEventoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoAllUpdatablePropertiesEquals(Evento expected, Evento actual) {
        assertEventoUpdatableFieldsEquals(expected, actual);
        assertEventoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoAutoGeneratedPropertiesEquals(Evento expected, Evento actual) {
        assertThat(actual)
            .as("Verify Evento auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoUpdatableFieldsEquals(Evento expected, Evento actual) {
        assertThat(actual)
            .as("Verify Evento relevant properties")
            .satisfies(a -> assertThat(a.getNoCia()).as("check noCia").isEqualTo(expected.getNoCia()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getFecha()).as("check fecha").isEqualTo(expected.getFecha()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getMotivoConsulta()).as("check motivoConsulta").isEqualTo(expected.getMotivoConsulta()))
            .satisfies(a -> assertThat(a.getTratamiento()).as("check tratamiento").isEqualTo(expected.getTratamiento()))
            .satisfies(a -> assertThat(a.getIndicaciones()).as("check indicaciones").isEqualTo(expected.getIndicaciones()))
            .satisfies(a -> assertThat(a.getDiagnostico1()).as("check diagnostico1").isEqualTo(expected.getDiagnostico1()))
            .satisfies(a -> assertThat(a.getDiagnostico2()).as("check diagnostico2").isEqualTo(expected.getDiagnostico2()))
            .satisfies(a -> assertThat(a.getDiagnostico3()).as("check diagnostico3").isEqualTo(expected.getDiagnostico3()))
            .satisfies(a -> assertThat(a.getDiagnostico4()).as("check diagnostico4").isEqualTo(expected.getDiagnostico4()))
            .satisfies(a -> assertThat(a.getDiagnostico5()).as("check diagnostico5").isEqualTo(expected.getDiagnostico5()))
            .satisfies(a -> assertThat(a.getDiagnostico6()).as("check diagnostico6").isEqualTo(expected.getDiagnostico6()))
            .satisfies(a -> assertThat(a.getDiagnostico7()).as("check diagnostico7").isEqualTo(expected.getDiagnostico7()))
            .satisfies(a -> assertThat(a.getObservacion()).as("check observacion").isEqualTo(expected.getObservacion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoUpdatableRelationshipsEquals(Evento expected, Evento actual) {
        assertThat(actual)
            .as("Verify Evento relationships")
            .satisfies(a -> assertThat(a.getTipoEvento()).as("check tipoEvento").isEqualTo(expected.getTipoEvento()))
            .satisfies(a -> assertThat(a.getCentro()).as("check centro").isEqualTo(expected.getCentro()))
            .satisfies(a -> assertThat(a.getCliente()).as("check cliente").isEqualTo(expected.getCliente()));
    }
}
