package com.devix.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FacturaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacturaAllPropertiesEquals(Factura expected, Factura actual) {
        assertFacturaAutoGeneratedPropertiesEquals(expected, actual);
        assertFacturaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacturaAllUpdatablePropertiesEquals(Factura expected, Factura actual) {
        assertFacturaUpdatableFieldsEquals(expected, actual);
        assertFacturaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacturaAutoGeneratedPropertiesEquals(Factura expected, Factura actual) {
        assertThat(actual)
            .as("Verify Factura auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacturaUpdatableFieldsEquals(Factura expected, Factura actual) {
        assertThat(actual)
            .as("Verify Factura relevant properties")
            .satisfies(a -> assertThat(a.getNoCia()).as("check noCia").isEqualTo(expected.getNoCia()))
            .satisfies(a -> assertThat(a.getSerie()).as("check serie").isEqualTo(expected.getSerie()))
            .satisfies(a -> assertThat(a.getNoFisico()).as("check noFisico").isEqualTo(expected.getNoFisico()))
            .satisfies(a -> assertThat(a.getFecha()).as("check fecha").isEqualTo(expected.getFecha()))
            .satisfies(a -> assertThat(a.getSubtotal()).as("check subtotal").isEqualTo(expected.getSubtotal()))
            .satisfies(a -> assertThat(a.getImpuesto()).as("check impuesto").isEqualTo(expected.getImpuesto()))
            .satisfies(a -> assertThat(a.getImpuestoCero()).as("check impuestoCero").isEqualTo(expected.getImpuestoCero()))
            .satisfies(a -> assertThat(a.getDescuento()).as("check descuento").isEqualTo(expected.getDescuento()))
            .satisfies(a -> assertThat(a.getTotal()).as("check total").isEqualTo(expected.getTotal()))
            .satisfies(a -> assertThat(a.getPorcentajeImpuesto()).as("check porcentajeImpuesto").isEqualTo(expected.getPorcentajeImpuesto())
            )
            .satisfies(a -> assertThat(a.getCedula()).as("check cedula").isEqualTo(expected.getCedula()))
            .satisfies(a -> assertThat(a.getDireccion()).as("check direccion").isEqualTo(expected.getDireccion()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFacturaUpdatableRelationshipsEquals(Factura expected, Factura actual) {
        assertThat(actual)
            .as("Verify Factura relationships")
            .satisfies(a -> assertThat(a.getCentro()).as("check centro").isEqualTo(expected.getCentro()))
            .satisfies(a -> assertThat(a.getCliente()).as("check cliente").isEqualTo(expected.getCliente()));
    }
}
