package com.devix.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ModeloAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModeloAllPropertiesEquals(Modelo expected, Modelo actual) {
        assertModeloAutoGeneratedPropertiesEquals(expected, actual);
        assertModeloAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModeloAllUpdatablePropertiesEquals(Modelo expected, Modelo actual) {
        assertModeloUpdatableFieldsEquals(expected, actual);
        assertModeloUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModeloAutoGeneratedPropertiesEquals(Modelo expected, Modelo actual) {
        assertThat(actual)
            .as("Verify Modelo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModeloUpdatableFieldsEquals(Modelo expected, Modelo actual) {
        assertThat(actual)
            .as("Verify Modelo relevant properties")
            .satisfies(a -> assertThat(a.getNoCia()).as("check noCia").isEqualTo(expected.getNoCia()))
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getPathImagen()).as("check pathImagen").isEqualTo(expected.getPathImagen()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModeloUpdatableRelationshipsEquals(Modelo expected, Modelo actual) {
        assertThat(actual)
            .as("Verify Modelo relationships")
            .satisfies(a -> assertThat(a.getMarca()).as("check marca").isEqualTo(expected.getMarca()));
    }
}
