package com.devix.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PaisAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaisAllPropertiesEquals(Pais expected, Pais actual) {
        assertPaisAutoGeneratedPropertiesEquals(expected, actual);
        assertPaisAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaisAllUpdatablePropertiesEquals(Pais expected, Pais actual) {
        assertPaisUpdatableFieldsEquals(expected, actual);
        assertPaisUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaisAutoGeneratedPropertiesEquals(Pais expected, Pais actual) {
        assertThat(actual)
            .as("Verify Pais auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaisUpdatableFieldsEquals(Pais expected, Pais actual) {
        assertThat(actual)
            .as("Verify Pais relevant properties")
            .satisfies(a -> assertThat(a.getNoCia()).as("check noCia").isEqualTo(expected.getNoCia()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaisUpdatableRelationshipsEquals(Pais expected, Pais actual) {
        // empty method
    }
}
