package com.devix.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProvinciaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProvinciaAllPropertiesEquals(Provincia expected, Provincia actual) {
        assertProvinciaAutoGeneratedPropertiesEquals(expected, actual);
        assertProvinciaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProvinciaAllUpdatablePropertiesEquals(Provincia expected, Provincia actual) {
        assertProvinciaUpdatableFieldsEquals(expected, actual);
        assertProvinciaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProvinciaAutoGeneratedPropertiesEquals(Provincia expected, Provincia actual) {
        assertThat(actual)
            .as("Verify Provincia auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProvinciaUpdatableFieldsEquals(Provincia expected, Provincia actual) {
        assertThat(actual)
            .as("Verify Provincia relevant properties")
            .satisfies(a -> assertThat(a.getNoCia()).as("check noCia").isEqualTo(expected.getNoCia()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProvinciaUpdatableRelationshipsEquals(Provincia expected, Provincia actual) {
        assertThat(actual)
            .as("Verify Provincia relationships")
            .satisfies(a -> assertThat(a.getPais()).as("check pais").isEqualTo(expected.getPais()));
    }
}
