package com.devix.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TipoCatalogoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoCatalogoAllPropertiesEquals(TipoCatalogo expected, TipoCatalogo actual) {
        assertTipoCatalogoAutoGeneratedPropertiesEquals(expected, actual);
        assertTipoCatalogoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoCatalogoAllUpdatablePropertiesEquals(TipoCatalogo expected, TipoCatalogo actual) {
        assertTipoCatalogoUpdatableFieldsEquals(expected, actual);
        assertTipoCatalogoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoCatalogoAutoGeneratedPropertiesEquals(TipoCatalogo expected, TipoCatalogo actual) {
        assertThat(actual)
            .as("Verify TipoCatalogo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoCatalogoUpdatableFieldsEquals(TipoCatalogo expected, TipoCatalogo actual) {
        assertThat(actual)
            .as("Verify TipoCatalogo relevant properties")
            .satisfies(a -> assertThat(a.getNoCia()).as("check noCia").isEqualTo(expected.getNoCia()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getCategoria()).as("check categoria").isEqualTo(expected.getCategoria()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoCatalogoUpdatableRelationshipsEquals(TipoCatalogo expected, TipoCatalogo actual) {
        // empty method
    }
}
