package com.devix.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TipoClienteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoClienteAllPropertiesEquals(TipoCliente expected, TipoCliente actual) {
        assertTipoClienteAutoGeneratedPropertiesEquals(expected, actual);
        assertTipoClienteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoClienteAllUpdatablePropertiesEquals(TipoCliente expected, TipoCliente actual) {
        assertTipoClienteUpdatableFieldsEquals(expected, actual);
        assertTipoClienteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoClienteAutoGeneratedPropertiesEquals(TipoCliente expected, TipoCliente actual) {
        assertThat(actual)
            .as("Verify TipoCliente auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoClienteUpdatableFieldsEquals(TipoCliente expected, TipoCliente actual) {
        assertThat(actual)
            .as("Verify TipoCliente relevant properties")
            .satisfies(a -> assertThat(a.getNoCia()).as("check noCia").isEqualTo(expected.getNoCia()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoClienteUpdatableRelationshipsEquals(TipoCliente expected, TipoCliente actual) {
        // empty method
    }
}
