package com.devix.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TipoDireccionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoDireccionAllPropertiesEquals(TipoDireccion expected, TipoDireccion actual) {
        assertTipoDireccionAutoGeneratedPropertiesEquals(expected, actual);
        assertTipoDireccionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoDireccionAllUpdatablePropertiesEquals(TipoDireccion expected, TipoDireccion actual) {
        assertTipoDireccionUpdatableFieldsEquals(expected, actual);
        assertTipoDireccionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoDireccionAutoGeneratedPropertiesEquals(TipoDireccion expected, TipoDireccion actual) {
        assertThat(actual)
            .as("Verify TipoDireccion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoDireccionUpdatableFieldsEquals(TipoDireccion expected, TipoDireccion actual) {
        assertThat(actual)
            .as("Verify TipoDireccion relevant properties")
            .satisfies(a -> assertThat(a.getNoCia()).as("check noCia").isEqualTo(expected.getNoCia()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoDireccionUpdatableRelationshipsEquals(TipoDireccion expected, TipoDireccion actual) {
        // empty method
    }
}
