package com.devix.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TipoProductoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoProductoAllPropertiesEquals(TipoProducto expected, TipoProducto actual) {
        assertTipoProductoAutoGeneratedPropertiesEquals(expected, actual);
        assertTipoProductoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoProductoAllUpdatablePropertiesEquals(TipoProducto expected, TipoProducto actual) {
        assertTipoProductoUpdatableFieldsEquals(expected, actual);
        assertTipoProductoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoProductoAutoGeneratedPropertiesEquals(TipoProducto expected, TipoProducto actual) {
        assertThat(actual)
            .as("Verify TipoProducto auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoProductoUpdatableFieldsEquals(TipoProducto expected, TipoProducto actual) {
        assertThat(actual)
            .as("Verify TipoProducto relevant properties")
            .satisfies(a -> assertThat(a.getNoCia()).as("check noCia").isEqualTo(expected.getNoCia()))
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoProductoUpdatableRelationshipsEquals(TipoProducto expected, TipoProducto actual) {
        // empty method
    }
}
