package com.devix.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UsuarioCentroAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUsuarioCentroAllPropertiesEquals(UsuarioCentro expected, UsuarioCentro actual) {
        assertUsuarioCentroAutoGeneratedPropertiesEquals(expected, actual);
        assertUsuarioCentroAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUsuarioCentroAllUpdatablePropertiesEquals(UsuarioCentro expected, UsuarioCentro actual) {
        assertUsuarioCentroUpdatableFieldsEquals(expected, actual);
        assertUsuarioCentroUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUsuarioCentroAutoGeneratedPropertiesEquals(UsuarioCentro expected, UsuarioCentro actual) {
        assertThat(actual)
            .as("Verify UsuarioCentro auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUsuarioCentroUpdatableFieldsEquals(UsuarioCentro expected, UsuarioCentro actual) {
        assertThat(actual)
            .as("Verify UsuarioCentro relevant properties")
            .satisfies(a -> assertThat(a.getNoCia()).as("check noCia").isEqualTo(expected.getNoCia()))
            .satisfies(a -> assertThat(a.getPrincipal()).as("check principal").isEqualTo(expected.getPrincipal()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUsuarioCentroUpdatableRelationshipsEquals(UsuarioCentro expected, UsuarioCentro actual) {
        assertThat(actual)
            .as("Verify UsuarioCentro relationships")
            .satisfies(a -> assertThat(a.getCentro()).as("check centro").isEqualTo(expected.getCentro()));
    }
}
